Issue 7  feature   sign up page
AfikNof95/WebDevelopmentProject pull request #14
Opened 2022-09-21 22:30 UTC by Omer-kaplan

Just made some commits, 
Afik - Don't need to go over yet

2022-10-21 13:12 UTC, linoyshokron requested changes
סיכום הערות שעלו לי:
1. הפרדה ברורה בין HTML, CSS ו-JS בקבצי EJS ב-VIEWS. ליצור קבצי CSS ו-JS סטטיים באותו שם של קובץ ה-EJS ולשים אותם תחת תיקיית PUBLIC. 
2. מה אומר שנחליט בנינו על קונבנציית שמות משתנים שקשורים ל-controllers או ל-models? ראיתי שקראת לזה למשל loginObject אז אולי נגדיר שקוראים לזה loginModel או loginController בהתאם לצורך? חמי אמר שזו קונבנצייה מוכרת ונפוצה באחת ההרצאות, גם יותר אינטואיטיבי להתמצא ככה בקוד לטעמי. תעדכן אותי מה דעתך.
3. בטח עעשית את זה אבל אני רק מוודאה - השמות של הפונקציות שהשתמש בהן מה-backend, וידאת שככה קוראים להן מול אפיק כן? אגב, אפיק ועדן אמרו שהם יכתבו בקובץ docs המשותף שלנו את שמות הפוקנציות ואת השדות של כל אובייקט שהם יוצרים לו model, ככה נוכל להיות בתיאום שוטף איתם ולא נהיה מופתעים ונצטרך לשנות דברים כל פעם שמישהו מאיתנו יעלה PR...

2022-10-21 13:12 UTC, linoyshokron commented on app.js
> +const serverPort = 3000;
אמור להיות גם clientPort אם ככה, לא?

2022-10-21 13:12 UTC, linoyshokron commented on app.js
> +const login = require("./routes/login");
אולי נקרא לזה loginRouter למען היישור קו בנינו

2022-10-21 13:12 UTC, linoyshokron commented on app.js
> +const signUp = require("./routes/signUp");
אולי נקרא לזה signUpRouter למען היישור קו בנינו

2022-10-22 19:16 UTC, Omer-kaplan commented on controllers/login.js
> +console.log(loginObject.getloginData());
Yes, Did so

2022-10-22 19:19 UTC, Omer-kaplan commented on views/login.ejs
> +  <body style="background: #fbf1ec !important">
indeed, did not know what is our convention, I'll move it out into Public

2022-10-23 19:10 UTC, Omer-kaplan commented on views/login.ejs
> +          <div class="col-6" style="background-color: #dfd8d2">
Did it :)

2022-10-23 19:10 UTC, Omer-kaplan commented on views/login.ejs
> +                style="
Changed :)

2022-10-23 19:11 UTC, Omer-kaplan commented on views/login.ejs
> +    <script type="text/javascript">
Done

2022-10-23 19:12 UTC, Omer-kaplan commented on app.js
> +const serverPort = 3000;
in Afiks branch (issue-18-_Feature_Sign_up_Backend)
Changes :)

2022-10-23 19:13 UTC, Omer-kaplan commented on app.js
> +const login = require("./routes/login");
I am about to change it to Afiks Convention --- Next Commit

2022-10-23 19:13 UTC, Omer-kaplan commented on app.js
> +const signUp = require("./routes/signUp");
As well in here

2022-10-24 19:12 UTC, linoyshokron approved these changes

2022-10-24 20:08 UTC, Omer-kaplan commented
solve conflicts when your branch is not up to dated

git fetch origin main:main
git rebase main
git push -f

2022-10-24 20:08 UTC, merged