Issue 20  feature  home page + global Navbar
AfikNof95/WebDevelopmentProject pull request #27
Opened 2022-10-31 00:18 UTC by Omer-kaplan

2022-11-05 11:10 UTC, AfikNof95 requested changes

2022-11-05 11:10 UTC, AfikNof95 commented on controllers/address.controller.js
> +      throw err.message;
תשנה כמו בקונטרולרים שלי שאני עושה res.status(400).json וכאלה

2022-11-05 11:10 UTC, AfikNof95 commented on controllers/address.controller.js
> +      throw err.message;
גם פה תחזיר שגיאות כמו שאני מחזיר אצלי בקונטרולר

2022-11-05 11:10 UTC, AfikNof95 commented on controllers/auth.controller.js
> +const accountView = (req, res) => {
כל מה שקשור לAccount תמחק כי עשיתי account.routes account.controller וכל הקבצים האלה.
בקובץ של auth נטפל רק במה שקשור בניהול של חיבור של משתמש מול השרת

2022-11-05 11:10 UTC, AfikNof95 commented on models/User.model.js
> +    address: { // make an array of addresses
זה לא צריך, במודל של כתובת נשים קישור למשתמש

2022-11-06 13:27 UTC, Omer-kaplan commented on controllers/address.controller.js
> +      // const address = await function();
השלמתי

2022-11-06 14:30 UTC, Omer-kaplan commented on controllers/address.controller.js
> +      // return res.render("accountAddress", { address: userAdresses });
השלמתי גם

2022-11-06 14:31 UTC, Omer-kaplan commented on controllers/address.controller.js
> +const delAccountAddresses = async (req, res) => {
פיקס שיניתי

2022-11-07 13:12 UTC, linoyshokron commented on views/homepage.ejs
> +            <div class="card category-crad">
crad lol

2022-11-07 13:13 UTC, AfikNof95 commented on views/homepage.ejs
> +            <div class="card category-crad">
בחיים לא הייתי שם לב לזה

2022-11-07 13:21 UTC, linoyshokron commented on views/homepage.ejs
> +    <script src="product.js" type="text/javascript"></script>
necessary?

2022-11-09 17:54 UTC, closed without merging